# Generated by Django 4.0.4 on 2022-05-26 21:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='name',
            new_name='character_name',
        ),
    ]
