# Generated by Django 4.0.4 on 2022-05-27 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0002_rename_name_character_character_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyalityLevelPoint',
            fields=[
                ('character', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='tibianusapp.character')),
                ('loyality_level_point', models.IntegerField()),
            ],
        ),
    ]
