# Generated by Django 4.0.4 on 2022-05-27 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0005_rank_character_rank_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loyalitytradepoint',
            name='character',
        ),
        migrations.AddField(
            model_name='character',
            name='loyality_level_points',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='loyality_trade_points',
            field=models.IntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='LoyalityLevelPoint',
        ),
        migrations.DeleteModel(
            name='LoyalityTradePoint',
        ),
    ]
