# Generated by Django 4.0.4 on 2022-05-27 16:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0006_remove_loyalitytradepoint_character_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achvievement_name', models.CharField(max_length=300, unique=True)),
                ('achvievement_description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='character',
            name='loyality_level_points',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='character',
            name='loyality_trade_points',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='character',
            name='achvievements',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='tibianusapp.achievement'),
        ),
    ]
