# Generated by Django 4.0.4 on 2022-05-27 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0007_achievement_alter_character_loyality_level_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='loyality_level_points',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='achievement',
            name='loyality_trade_points',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
