# Generated by Django 4.0.4 on 2022-05-27 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0009_rename_loyality_level_points_achievement_loyality_level_point_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='achvievement',
        ),
        migrations.CreateModel(
            name='CharacterAchievements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achievement_gain', models.DateField()),
                ('achievement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tibianusapp.achievement')),
                ('character', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tibianusapp.character')),
            ],
        ),
    ]
