# Generated by Django 4.0.4 on 2022-05-27 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0013_alter_characterachievement_achievement_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='characterachievement',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tibianusapp.character'),
        ),
    ]
