# Generated by Django 4.0.4 on 2022-05-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0014_alter_characterachievement_character'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='max_loyality_level_point',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='max_loyality_trade_point',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_loyality_level_point',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_loyality_trade_point',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
