# Generated by Django 4.0.4 on 2022-05-28 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0015_rank_max_loyality_level_point_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='rank_loyality_level_point',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
