# Generated by Django 4.0.4 on 2022-06-01 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0022_alter_activetask_character'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activetask',
            name='added',
            field=models.DateField(auto_now_add=True),
        ),
    ]
