# Generated by Django 4.0.4 on 2022-06-06 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0024_alter_character_rank_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Monster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monster_name', models.TextField(max_length=250, unique=True)),
                ('monster_exp', models.BigIntegerField()),
            ],
        ),
    ]
