# Generated by Django 4.0.4 on 2022-06-11 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0026_alter_monster_monster_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='max_experience_permonster',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_experience_permonster',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
