# Generated by Django 4.0.4 on 2022-06-11 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0027_rank_max_experience_permonster_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rank',
            name='max_experience_pertask',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='rank',
            name='min_experience_pertask',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
