# Generated by Django 4.0.4 on 2022-06-12 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tibianusapp', '0028_rank_max_experience_pertask_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rank',
            old_name='rank_loyality_level_point',
            new_name='max_rank_loyality_level_point',
        ),
        migrations.AddField(
            model_name='rank',
            name='min_rank_loyality_level_point',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
